# Generated by Django 3.1.7 on 2021-02-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='buyPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
