# Generated by Django 3.1.7 on 2021-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_buystock_buyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='currentPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buystock',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
