# Generated by Django 3.1.7 on 2021-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_auto_20210225_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystock',
            name='id',
        ),
        migrations.AddField(
            model_name='buystock',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buystock',
            name='tickerSymbol',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
