# Generated by Django 3.1.7 on 2021-02-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_auto_20210225_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAndTime', models.DateTimeField(auto_now_add=True)),
                ('stockTicker', models.CharField(max_length=15)),
                ('buyPrice', models.FloatField(default=0.0)),
                ('shares', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='BuyStock',
            new_name='Stocks',
        ),
    ]
