# Generated by Django 3.1.7 on 2021-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0005_auto_20210226_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='buyPrice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transactionType',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
